### ISSUE TITLE
Hardcoded Ollama model name prevents using custom models

### ISSUE THREAD

**Issue by lawrencejesse** [ToolUse/whisperbox#17]
## Bug Description
The Ollama model name is hardcoded to `"llama3.1"` in `ai/llm.py`, which prevents using other Ollama models even when specified in `config.yaml`. This same issue affects other AI providers as their models are also hardcoded.

## Current Behavior
- `config.yaml` allows setting `default_model: llama3.2:1b` or other models like `gpt-4-0125-preview`
- But the code in `ai/llm.py` has hardcoded defaults:

```python
DEFAULT_MODELS = {
    "ollama": "llama3.1",
    "groq": "llama-3.1-70b-versatile",
    "anthropic": "claude-3-5-sonnet-20241022",
    "openai": "gpt-4-0125-preview",
}
```

- This causes errors when trying to use other models: "model 'llama3.1' not found"
- The same issue would affect OpenAI users trying to use different models like `gpt-4o-mini`

## Expected Behavior
The code should respect the model name set in `config.yaml` instead of using the hardcoded default. For example:

```yaml
ai:
  default_model: gpt-4o-mini
  default_provider: openai
  openai:
    api_key: your_api_key_here
```

or

```yaml
ai:
  default_model: llama3.2:1b
  default_provider: ollama
```

## Suggested Fix
Update the `AIService` class to check `config.yaml` before falling back to `DEFAULT_MODELS`:

```python
def __init__(self, service_type: Optional[str] = None, model: Optional[str] = None):
    self.service_type = service_type.lower() if service_type else "ollama"
    # Check config first, then fallback to default
    self.model = (
        model or 
        config.ai.get('default_model') or 
        self.DEFAULT_MODELS[self.service_type]
    )
```

## Steps to Reproduce
1. Install Ollama and pull a different model (e.g., `ollama pull llama3.2:1b`)
2. Set up `config.yaml` with:

```yaml
ai:
  default_model: llama3.2:1b
  default_provider: ollama
```

3. Run WhisperBox
4. Observe error about "llama3.1" not found, despite config specifying a different model

The same issue occurs when trying to use different OpenAI models or models from other providers.
